#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id: MakeWorkspaceCreator.pm 2035 2011-10-06 15:05:21Z johnnyw $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../MPC/mwc.pl -type make IntervalTree.mwc
#
#----------------------------------------------------------------------------


all: IntervalTree

clean depend generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.IntervalTree $(@)

.PHONY: IntervalTree
IntervalTree:
	@$(MAKE) -f Makefile.IntervalTree all

project_name_list:
	@echo IntervalTree
